[package]
name = "torqtui"
description = "TorQ: fast torrent finder and downloader (daemon, TUI, CLI)"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "torq"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
reqwest.workspace = true
axum.workspace = true
serde.workspace = true
base64.workspace = true
serde_json.workspace = true
dirs.workspace = true
torq-core = { path = "../torq-core", version = "0.1.1" }
torq-sources = { path = "../torq-sources", version = "0.1.1" }
torq-tui = { path = "../torq-tui", version = "0.1.1" }
